### ISSUE TITLE
Wildcard for monospace display

### ISSUE THREAD

**Issue by gregoryo2014** [protz/thunderbird-conversations#1021]
Is there a wildcard feature for which messages to display monospaced? I would like root@.\* or root@\* or somesuch. I've tried a few combinations and none seem to work.

Thanks,
Greg.

**Comment by protz** [comment]
I don't there is, but I'd happily take a patch for it (i.e. if first 
character of the entry is "/", then interpret it as a regexp, otherwise, 
interpret it as a regular string).

Thanks,

Jonathan

**Comment by Standard8** [comment]
The need for monospaced is much reduced now, bugzilla supports html emails, which is the case it was originally introduced for.

Additionally, the code it requires adds more complexity that we don't really want at the moment, as we're simplifying what we can so that it is more supportable, and hopefully will be able to continue alongside Thunderbird in the future.

I've also not included the monospace feature in the recent versions, and no-one has complained yet. Whilst I don't like removing features, we also have to be pragmatic.

Hence, I'm closing this out as we won't be fixing it.

**Comment by gregoryo2014** [comment]
I can't fault the idea of making the plugin more sustainable. Clearly it never got important enough for me to figure out submitting a PR!
