### ISSUE TITLE
Add-on broken in latest TB (46.0) betas

### ISSUE THREAD

**Issue by darrenkenny** [protz/thunderbird-conversations#1056]
It looks like there have been some JS changes in TB 46 beta that is causing the loading
of the conversations add-on to fail.

For example the Array comprehension doesn't seem to work any more, etc.

Any chance of the add-on being updated to deal with these issues?

**Comment by protz** [comment]
Please install 
http://jonathan.xulforum.org/files/gcv-nightlies/201511251059-master.xpi 
and close this issue if it fixes your problem.

Thanks,

Jonathan

**Comment by darrenkenny** [comment]
Thanks for the quick response!

Unfortunately, that's the version that I'm running - always have tried to run the latest that you
have available there.

So, here are the exact errors that I'm seeing when I enable the add-on after restarting TB with it
disabled:

`Timestamp: 29/01/2016 12:11:34
Warning: expression closures are deprecated
Source File: resource://conversations/modules/prefs.js
Line: 80, Column: 22
Source Code:
  split: function (s) Array.map(s.split(","), String.trim).filter(String.trim).map`

`1454069494931	addons.xpi	WARN	Exception running bootstrap method startup on gconversation@xulforum.org: SyntaxError: missing ] after element list (resource://conversations/modules/prefs.js:115:21) JS Stack trace: @log.js:3:1 < startup@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///D:/Users/darrenk/AppData/Roaming/Thunderbird/Profiles/t4tlfmds.default/extensions/gconversation@bootstrap.js:170:3 < this.XPIProvider.callBootstrapMethod@XPIProvider.jsm:4658:9 < this.XPIProvider.updateAddonDisabledState@XPIProvider.jsm:4785:13 < AddonWrapper.prototype.userDisabled@XPIProvider.jsm:7062:9 < set_userDisabled@extensions.xml:1072:11 < oncommand@about:addons:1:1`

`Warning: attempting to write 11491 bytes to preference extensions.xpiState. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file.`

Thanks,

Darren

**Comment by protz** [comment]
Are you on trunk ? Beta is 44 right now

**Comment by darrenkenny** [comment]
Apologies, it is EarlyBird, so yes trunk. Sorry for the confusion.

**Comment by protz** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Array_comprehensions#Differences_to_the_older_JS1.7.2FJS1.8_comprehensions

Gosh... they again removed syntax.

It's a silly syntactic change but I need to be back home with my copy of 
Thunderbird trunk in order to make it happen.

I will be extremely busy in the upcoming few days, and it's really a 
simple change:

[X for (foo)] becomes [for (foo) X]

Here's all the occurrences in conversations :

content/stub.compose-ui.js
609:          let to = [asToken(null, name, email, null) for ([name, 
email] of params.to)];
610:          let cc = [asToken(null, name, email, null) for ([name, 
email] of params.cc)];
611:          let bcc = [asToken(null, name, email, null) for ([name, 
email] of params.bcc)];
641:          let to = [asToken(null, name, email, null) for ([name, 
email] of params.to)];

content/stub.xhtml
482:          let msgHdrs = [msgUriToMsgHdr(x) for (x of 
params.urls.split(","))];
621:              [asToken(null, name, email, null) for ([{ name, email 
}] of items.map(parseMimeLine))]

modules/assistant.js
107:  this.customizations = [new PrefCustomization(p) for (p of aParams)];
112:    return [x.install() for (x of this.customizations)];

modules/conversation.js
328:  //   [toMsgHdr(x) for (x of this.messages)]
696:    let i = [x.message for (x of this.messages)].indexOf(aMessage);
725:        [msgDebugColor(x) + x.debug for (x of aMessages)].join(" "), 
Colors.default);
730:      [(x.message._conversation = this) for (x of aMessages)];
978:      [msgDebugColor(x) + x.debug for (x of this.messages)], 
Colors.default);
1135:    return [toMsgHdr(x) for (x of this.messages) if (toMsgHdr(x))];

modules/message.js
239:    msgNodes = [x for (x of msgNodes)];
1760:      [x.value for (x of aGlodaMsg.mailingLists)];

modules/misc.js
88:  return [groups[id] for (id of orderedIds)];

modules/monkeypatch.js
286:      let urls = [msgHdrGetUri(x) for (x of msgHdrs)].join(",");
418:            let newlySelectedUris = [msgHdrGetUri(x) for (x of 
aSelectedMessages)];

modules/plugins/enigmail.js
528:  [treeController[i] = x for ([i, x] of entries(oldTreeController))];

modules/prefs.js
115:        [x(aData, v) for (x of this.watchers)];
123:        [x(aData, v) for (x of this.watchers)];

modules/stdlib/misc.js
375:  return [[a1[i], a2[i]] for (i of range(0, a1.length))];

modules/stdlib/send.js
290:  references = ["<"+x+">" for (x of references)];
292:  [fields.addAttachment(x) for (x of attachments)];

If you have time to give a hand, that would be the best way to fix your 
issue and make sure it happens in a reasonable timeframe :)

**Comment by protz** [comment]
A better fix would be to switch to map/filter + arrow functions...

**Comment by darrenkenny** [comment]
I've given a shot, but it's incomplete, in that while I'm not seeing any errors on the console any more, I'm also not seeing my messages using a conversation view :(

I'm afraid that I can't spend any more time debugging this since I really don't know what I'm
looking for here - but you might be able to pick it out quicker given that you wrote it :)

Hope that it helps at least.

So, for now, here's a diff that I've generated, attached:

[conv.diff.txt](https://github.com/protz/thunderbird-conversations/files/112404/conv.diff.txt)

**Comment by Dexterp37** [comment]
This was fixed :)

**Comment by msprotz** [comment]
https://jonathan.protzenko.fr/thunderbird-conversations/ ← build there

**Comment by darrenkenny** [comment]
Excellent - many thanks! Seems to be working well so far...
