### ISSUE TITLE
Linux crash after hitting Reply, Forward buttons

### ISSUE THREAD

**Issue by martinbx** [protz/thunderbird-conversations#1059]
Using Conversation 2.10.2 on Thunderbird 38.5.1 Ubuntu 15.10.
I experience crash of whole Ubuntu OS occasionally if I click the Reply, Reply All or Forward buttons at the end of message in Conversation view. It is not happening all the time, likely every month or two.
For clarity ![buttons causing crash](https://cloud.githubusercontent.com/assets/17177334/12976170/712d5c76-d0c2-11e5-99cd-3c7a3a47f418.png)
Thanks'

**Comment by pianoslum** [comment]
A Conversations-Bug should not cause Thunderbird to crash, let alone Ubuntu!
Is your OS otherwise unstable sometimes?

I fear that nobody will be able to reproduce that bug, especially if it only happens occasionally...
One idea would be to look at the error console of thunderbird after such a crash...

**Comment by protz** [comment]
See https://support.mozilla.org/en-US/kb/thunderbird-crashes -- most likely a thunderbird issue

**Comment by martinbx** [comment]
You are right, Thunderbird crashes were caused also by clicking main menu items in Th UI. After manual upgrade to Thunderbird 38.6.0 it did not happen any more. Sorry.
