### ISSUE TITLE
Feature request: Allow to exclude some accounts from being tagged as "Me" in conversations

### ISSUE THREAD

**Issue by garfae** [protz/thunderbird-conversations#1078]
This is useful in any situation where shared accounts are accessed by multiple users.
In that case, the account is added in TB but should not be flagged as "Me".

Dirty fix: Never flag as "Me" anything that is in the address book.
Less dirty fix: Add a checkbox option to only tag as "Me" the identities of the account where the email is stored.
Perfect fix: Add an option to input comma-separated email addresses which are NOT to be tagged as "Me".

**Comment by protz** [comment]
We already display `Me (foo@bar.com)` to disambiguate, so the scenario you describe would add extra complexity. Furthermore, it seems like a minor tweak that caters to a specific audience, and not worth a general option.

**Comment by garfae** [comment]
We do not see how NOT displaying something would add extra complexity?... 

If you do not want to implement trivial options that would cater to the needs of what you consider a small part of your userbase, then at least please add an option to disable the "Me" feature entirely?

Thanks for the awesome module anyway!

**Comment by protz** [comment]
Well, it's an extra option that I won't test. For every option you add,
it's one more combination that you add; for n options, you have at least 2ⁿ
possible combinations. I would have to add user interface in the options
pane, add code here and there to handle your option... this would
complexify the code just for your own benefit, since you're the only person
who ever asked for that particular feature, out of 100,000 users and 5
years of existence. So, I don't think this is the right tradeoff. I can't
implement every option that users request!
