### ISSUE TITLE
Remember opened tabs with conversations

### ISSUE THREAD

**Issue by diegogurpegui** [protz/thunderbird-conversations#1091]
I close Thunderbird with some tabs opened (Conversation tabs), but then when I open Thunderbird again, none of those remembered tabs open correctly. They keep with the title "Conversation Reader", the conversation never loads and the tab content is just blank.

This used to work great since the beginning. However since the last update of Thunderbird and/or Conversations (not sure which) it stopped working.
If I open a new conversation from the Inbox, it opens perfectly.

**Comment by diegogurpegui** [comment]
If it's any help: I use a Master Password

**Comment by Linuspogo** [comment]
I have the exact same issue, on both the stable and the beta version of Thunderbird. I don't use a Master Password.

**Comment by francky37** [comment]
Same issue here, "Loading.." is displayed at the top, but nothing happens

**Comment by jfrancin** [comment]
Exact same symptoms, using Thunderbird 45.1.1 and Thunderbird Conversations 2.11.4.  This used to work.

**Comment by theWoosh** [comment]
I too have this problem - it has happened intermittently (and annoyingly) in recent months but now it happens every time I restart thunderbird... does anyone have any clues? I am using thunderbird 45.1.1 on Windows 8.1...

**Comment by theWoosh** [comment]
how do we escalate this problem?

**Comment by xi** [comment]
I did some debugging and found that it works correctly if I remove the `_selectionChanged()` check from [`_Conversation_outputMessages()`](https://github.com/protz/thunderbird-conversations/blob/9704a57/modules/conversation.js#L815). This seems to be very old code, so I do not really dare to touch it. But maybe it can just be removed.

**Comment by francky37** [comment]
To xi,
Thank you very much, I removed the lines and it works perfectly now.

**Comment by theWoosh** [comment]
hi xi - where do I find this file to modify? I have had this problem occasionally for more than a year, but in the last weeks it has become chronic...

**Comment by xi** [comment]
**Warning**: I do not recommend to do this. It should rather be fixed upstream. Do this at your own risk.

Go to your profile's extension folder (mine is at `~/.thunderbird/{profilename}/extensions/`). There should be a file called `gconversation@xulforum.org.xpi`. Create a folder called `gconversation@xulforum.org` (same name without extension), and unpack the file to that folder. The file you need to edit is `modules/conversation.js`.

**Comment by tvankess** [comment]
Same problem, happening on every Thunderbird launch recently (TB 45.1.1, "up to date"). I don't want to dive into the type of edits/changes shown here, in case something goes sideways... Any suggestions on where else I might search (forums, etc) for an answer?

**Comment by xi** [comment]
> Any suggestions on where else I might search (forums, etc) for an answer?

I think this is a bug in the plugin and unfortunately there is no way around fixing it in the plugin.

@protz There seems to be a lot of interest in fixing this. I would like to help, but I really need some background information on [`_Conversation_outputMessages()`](https://github.com/protz/thunderbird-conversations/blob/9704a57/modules/conversation.js#L815).

**Comment by fretsbr549** [comment]
Same problem going on here for at least 6 months or more and it is costing me business. After a shutdown and restart all conversations just shows 'Conversation' in the tab and 'Loading' inside the tab.
I wish someone would could fix this for us lesser tech people.

**Comment by tvankess** [comment]
I did fix the problem, by disabling all my add-ons. I'm now re-enabling them one by one to see if it comes back.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the Rogers network.                                                                                                                                                                                                                From: fretsbr549Sent: Friday, July 29, 2016 11:49 AMTo: protz/thunderbird-conversationsReply To: protz/thunderbird-conversationsCc: tvankess; CommentSubject: Re: [protz/thunderbird-conversations] Remember opened tabs with conversations (#1091)Same problem going on here for at least 6 months or more and it is costing me business. After a shutdown and restart all conversations just shows 'Conversation' in the tab and 'Loading' inside the tab.
I wish someone would could fix this for us lesser tech people.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by fretsbr549** [comment]
I disabled all the add ons except conversation of course, closed all the 'loading' tabs, restarted TB, opened some conversations, restarted TB again and have the same results. Something is amiss in the code. It is broken.

**Comment by fretsbr549** [comment]
I disabled the Conversation add on, removed it, reinstalled it, waited for approx 30 min while it indexed then manually closed the box and no change.
The activity manager showed nothing of relevance.

**Comment by jfrancin** [comment]
If you follow the instructions written in the comment stream above by user @xi on the 20th and 22nd of June, you can remove the offending code in one of the JavaScript files that make up the add-on package. Unfortunately, it's really the sort of thing the package owner should be doing.

**Comment by fretsbr549** [comment]
Thanks for everyone's input.
I just followed the instructions by @xi above with no change. However I have a question. He said create a new folder gconversation@xulforum.org without the extension xpi which I did. I created it as a folder within  ~/.thunderbird/{profilename}/extensions/. Then I unpacked the file to there and edited it. He did not say where that folder should be so I assumed to put it there. It didn't make any difference. 
I commented out the lines like this:
    //if (this._selectionChanged()) {
    //  Log.debug("Selection changed, aborting...");
    //  return;
I have TB 45.2.0 and TB Conversations 2.11.4
Still broken. Any thoughts? 
It would be nice of the owner to step in here.

**Comment by jfrancin** [comment]
I made the exact same edit. But I also made a copy of the zipped archive, freshened it, and restarted Thunderbird. I suspect that Thunderbird will only use the 'loose' directory if the archive doesn't exist.

Here's what I did in detail:

After making the edit to conversation.js in the gconversation@xulforum.org/modules directory, I then went up a level:
% cd ..
% pwd
/Users/jfrancin/Library/Thunderbird/Profiles/nka7pikt.default/extensions/gconversation@xulforum.org

Then did a diff of the change:

% diff modules/conversation.js~ modules/conversation.js
815,818c815,818
<     if (this._selectionChanged()) {
<       Log.debug("Selection changed, aborting...");
<       return;
<     }
---
>     //    if (this._selectionChanged()) {
>     //      Log.debug("Selection changed, aborting...");
>     //      return;
>     //    }

Then I made a copy of the zip file (in the directory above) just in case:

% cp ../gconversation\@xulforum.org.xpi ../gconversation\@xulforum.org.xpi.original

Next I used zip's 'freshen' function to only replace changed files:

zip -f -9 -r ../gconversation\@xulforum.org.xpi *
freshening: modules/conversation.js (deflated 71%)
freshening: modules/conversation.js~ (deflated 71%)

Then I restarted Thunderbird. And the conversations came back.

**Comment by fretsbr549** [comment]
I made the changes that JFrancin suggested. It proved that the conversation.js file does need to be placed inside of the .xpi pack file to work as he had mentioned. I supposed if the .xpi file did not exist it would go to the directory that was created in the instructions from @xi also as JFrancin suggested.

With the edited file in place the end result was not acceptable in my case. Every time I clicked on a conversation to open it, it would open every email associated with that conversation in a separate tab. So if there were 20 emails there would be 20 new tabs. Clearly out of control. But it would save those tabs and open them when TB was closed and restarted. I thought perhaps there was a setting to specify open all emails inline but could find nothing. I ran the setup assistant from within the add-on hoping a re-index of some sort would correct it but to no avail.

At this point I put the conversation.js file back to where it was by restoring the original unaltered file. And it behaves just as it did to begin with. It will not open the conversation when TB is closed and reopened. Is just says "Conversation Reader"  in the tab header and "loading..." in the screen.

So the edit suggested is a fix for for some but not all. I think we can all agree the average user should never be expected to edit executable files. So who knows what the real problem is. All my add on's are disabled but not uninstalled.

I don't know where else this could go except to the developer. There is a known problem and if one knew the code well enough one could probably find other areas that may be similarly tied together. But it is beyond me. It's a shame because I keep track of what my customers order with this conversation. It ultimately ends up in an accounting invoice but if there is ever a question and there often is the conversation is the proof of the pudding. I hope it can get fixed.

**Comment by fretsbr549** [comment]
Looks like this is not being considered by the owner. Does anyone know of a substitute for this plugin? Or suggestions on a different email client that has a conversation mode?

**Comment by protz** [comment]
@daesters can you submit a pull request on the main repository?

Was the method removed in some underlying Thunderbird change? Did you get to the bottom of this?

Thanks,

Jonathan

**Comment by protz** [comment]
Fixed, along with a pre-release build at https://jonathan.protzenko.fr/thunderbird-conversations/

**Comment by snowbound** [comment]
Extension no longer works in TB 52.0.1
