### ISSUE TITLE
Latest pre-release version stopped working in TB 56.0b2 (macOS)

### ISSUE THREAD

**Issue by scheinercc** [protz/thunderbird-conversations#1221]
Hi there,

I had already the latest pre-release version 201706111701-2.13+.xpi from https://jonathan.protzenko.fr/thunderbird-conversations/ during TB 55.0b1 installed and it worked fine. Now it just stopped after the update to TB 56.0b2 (can't remember if it also happened with TB 56.0b1...).
As the version number in the extensions' pane still showed 2.12pre* I uninstalled and reinstalled it. Next I tried running the setup assistent, but after 30 minutes with spinner + "working ..." I figured it won't finish (if it actually had started yet).

_* version number shown in extensions' pane after installing 201706111701-2.13+.xpi_
<img width="714" alt="tbc-pre-res-number" src="https://user-images.githubusercontent.com/817856/29255782-00b8c78c-80e8-11e7-9852-b17119a6f672.png">

**Comment by Standard8** [comment]
I used [mozregression](https://mozilla.github.io/mozregression/) to take a look at this and found https://hg.mozilla.org/comm-central/pushloghtml?fromchange=fb6824894528f321f862f7d9eac98c95a53a2417&tochange=8395d8712176cb6d21a0b7193faf54855c912ee6 as the regression range.

Of those, https://hg.mozilla.org/comm-central/rev/0bcc573012c9 seems to be the culprit, and I've got a patch locally that I'll push in a moment.

**Comment by Standard8** [comment]
Hi everyone. I have just uploaded a pre-release version with the fix for this in to https://addons.mozilla.org/thunderbird/addon/gmail-conversation-view/#beta-channel (under the Development Channel section). The version number is 2.13pre2.

If you download from there you'll be on our development channel and will continue to get early updates of releases for testing.

I'm hoping to release 2.13 in a day or so, once people have had chance to test it.

If you find more problems, please open new issues for them.

**Comment by thescotthughes** [comment]
I installed the new version. I am still not seeing most sent messages in conversation view.

I tried both the development version linked above and the 2017-09-05 release (201709051426-2.13+.xpi). Neither worked.
