### ISSUE TITLE
Latest master: check marking as read is working correctly

### ISSUE THREAD

**Issue by Standard8** [protz/thunderbird-conversations#1378]
I've just pushed the message list transition of React to the master branch. This has switched us away from jQuery.

I'm not 100% sure if all the marking as read is working correctly.

In particular, for those that don't mark as read immediately, I'm not sure that scrolling past messages will mark them as read.

I've also not tested marking read after a delay.

**Comment by Hi-Angel** [comment]
Hmm, it's possible that this is an issue I'm often experiencing. With latest master, it often happens that if I press <kbd>n</kbd> to switch to next unread message, this message is not being rendered. Since that moment none of the mails I click can be rendered. To make mails get rendered again I need to switch to another folder, and then back.

I haven't found reliable steps to reproduce this, it happens sporadically. I think it happens ≈3-4 times a day on average *(depends on amount of received mails though)*.

**Comment by Standard8** [comment]
> With latest master, it often happens that if I press n to switch to next unread message, this message is not being rendered. Since that moment none of the mails I click on can be rendered

The useful thing in this case is any errors on the Error Console (under Tools -> Developer Tools).

However, I hit this once the other day, and I caught the error message and stack. I've just pushed a few extra checks which will hopefully stop that from happening.
