### ISSUE TITLE
Mouseover Popup moves on mouse down and doesn't recognize click on buttons

### ISSUE THREAD

**Issue by Stefan1232** [protz/thunderbird-conversations#1381]
* **Thunderbird version:** 60.9.1
* **Thunderbird Conversation version:** 2.14.7
* **Operating System:** Win10 

**What did you do?**
I hoover the mouse over the senders email address and a small popup window appears. I tried to click the "Send Email" button.

**What did you expect to happen?**
A compose new Email window should open.

**What actually happened?**
When I press the mouse button (Mouse-Down), the pop-up window moves. Thus, the mouse pointer is not any longer over the "Send Email button", and when I release the mouse button, nothing happens. I tried to move the mouse pointer to the new window position as well, but the mouse release isn't recordnized as well. 

Window Position before I click the button:
![grafik](https://user-images.githubusercontent.com/45255111/69222146-2650cf80-0b79-11ea-8036-48466d4373cc.png)
Window Position as soon as the mouse button is pressed: (MouseDown):
![grafik](https://user-images.githubusercontent.com/45255111/69222209-4c766f80-0b79-11ea-9817-b0adb63075ff.png)

This behavior occurs most of the time, but not always. Sometimes, the pop-up stays where it is.

The same happens on "Copy Email Address"

**Comment by Standard8** [comment]
Thank you for the report.

I believe this is fixed on the latest Conversations - the v2.15.x series, if not, it is definitely fixed on the latest master which I'm hoping to release in a few weeks once I've got it back to parity with the current release.

Unfortunately due to the changes between Thunderbird 60 and 68, the 2.15.x series is only compatible with 68 and later, and it isn't possible to support the 60.x series as well.

For now I'll close this as I've not seen it recently working with the latest code. Please feel free to reopen later if there is still an issue there.

**Comment by Stefan1232** [comment]
Thanks! I just updated to TB68 and it solved the problem.
