### ISSUE TITLE
Gray background for message card (resurfaced)

### ISSUE THREAD

**Issue by fllp** [protz/thunderbird-conversations#1388]
* **Thunderbird version: 68.2.1**
* **Thunderbird Conversation version: 2.15.13**
* **Operating System: Linux Mint (GTK based Desktop)**

Related #1191 #1159 

---

Same problem has resurfaced for the latest Thunderbird version. See screenshot and old issues.
![translucent](https://user-images.githubusercontent.com/15898292/70347501-92f5ea80-1858-11ea-80c7-096a5271e6da.png)

**Comment by laspic** [comment]
Same here. But because I'm new on Thunderbird Conversations (since mid-December), I never noticed that it wasn't a normal behavior. It thought it was only a (strange) choice of the developer(s). ;-)
I even don't know what should be the normal display on my system...

- **Thunderbird version:** 68.2.2
- **Thunderbird Conversation version**: 3.0.10
- **Operating System:** Xubuntu 18.04 + Openbox (GTK based Desktop)

**Comment by Standard8** [comment]
I've just pushed a fix that will hopefully fix this - I ended up removing the background styles, as they didn't seem necessary now (I checked on all three platforms, though I may have missed something).

We'll see what happens in the next roll-out.
