### ISSUE TITLE
Ctrl+r doesn't work in conversations?

### ISSUE THREAD

**Issue by qazip** [protz/thunderbird-conversations#1399]
I am using the latest thunderbird and the latest version of this addon. I've noticed that the shortcut for replying (ctrl+r) doesn't seem to work in conversations.. It works very seldomly, but I can't reproduce...

Are you aware of this?

EDIT: Seems like the thread needs to be expanded for the shortcut to work.

EDIT2: It also works if I **click** on the message in the preview. It is annoying having to click on the mssage to be able to use the shortcut. It should be focused by default, should it not?

**Comment by Standard8** [comment]
The problem with reply in message threads is that if you're focussed in the message list, and have say more than one end-point, which one would you expect to respond to? It would be ambiguous.

If you take what's in the message pane (or if the message pane is focussed), you could say it is the one shown in the message pane, but then you also get into questions like should it be the message at the top, with most display, what about if it is 50/50 etc. 

I suspect we're actually following what Thunderbird does here, we're not actually implementing anything extra. At the moment, I'm inclined to keep it that way, rather than complicating things. I'd rather not add too much new stuff at the moment, given the underlying changes in Thunderbird that are happening.

**Comment by qazip** [comment]
I don't know if it is thunderbird or if it is conversations but something is fully bugged on my end. Even after clicking on a message (in the mail preview window), ctrl+r doesn't work. It used to, but now it doesn't. It was either a thunderbird update or a conversations update. Can you reproduce?

**Comment by Standard8** [comment]
ctrl-r works fine for me as long as there is a single message selected, i.e. there is not a collapsed thread.

**Comment by qazip** [comment]
That is weird, because 2 weeks ago the behaviour was different! I was able to reply by using ctrl+r if I clicked on the message on the right-side panel (email preview panel), regardless if the thread was collapsed or not (in the mail list panel, left side panel)..

**Comment by Standard8** [comment]
I just checked back to Thunderbird 60 with the version of Conversations there, and it isn't possible to ctrl-r if the thread is collapsed, even with the message pane focussed.

I'm going to close this out, as I think if there's any issue here it is with Thunderbird and not Conversations. You can try filing an issue at https://bugzilla.mozilla.org/ if you want. Though I'm not sure they'll be able to do much, as there's a logic issue of which message are you actually attempting to respond to.

**Comment by qazip** [comment]
Can we look into this again @Standard8? This is still bugging me. If I have a conversation going and I click Ctrl+r, I expect it to reply to the latest message, or whichever is selected. In the case that there is more than one selected, than probably do nothing, which is the default behaviour right now.

I come from Fastmails webclient, which is, IMO, the best on the planet, and they do this perfectly. I am so used to keyboard shortcuts that I hate having to use the mouse in order to reply.
