### ISSUE TITLE
Feature Request: Manual Messages Threading

### ISSUE THREAD

**Issue by sambul13** [protz/thunderbird-conversations#1410]
Thunderbird and TB Conversations are at times unable to properly thread messages into conversations. It usually occurs due to missing _In-Reply-To_ or _Reference_ fields in the message headers. While we can discuss all day long that the user should ask their contacts to use a different email client, or file a bug report about the existing client, the reality is it seldom works. Good example is TB itself - many bugs takes 30 years to start thinking about, but still never do anything to fix. For example, many companies use social media for CSR contacts. But Twitter Messenger fails to include Reference line in the header, and this goes for 20 years.

Wishful thinking never works. Instead of blaming the user or company, or teaching them what they should do, is it possible to offer a new feature in TB Conversations: **Manual Messages Threading** . It can offer to edit message header, i.e. by adding _Reference_ field to it manually or automatically, and saving the message in the same mailbox. After that they will be auto grouped normally.

Currently I do it manually as described in [“Manual threading” in Thunderbird](https://superuser.com/questions/126356/manual-threading-in-thunderbird), because all TB extensions mentioned in it weren't updated to TB 68. Namely, I do the following:

_copy a message to desktop -> open in Notepad -> add "References: <sometext@somewhere.com>" before Subject line in Header -> Save -> drag back to same TB Inbox -> delete deskop copy_

**Comment by Standard8** [comment]
Hi, I can appreciate the desires to have better threading, and for manual threading, and I wouldn't argue against them.

Unfortunately, Thunderbird has had lots of changes recently and there are changes ongoing. Due to this we already have a lot of work still to do to get Conversations into a place where it will be able to keep working in future without significant amounts of maintenance all the time. Therefore I'm not prepared to accept new features at this time.

(The lack of Thunderbird WebExtension APIs that would allow this to happen also doesn't help, but isn't exclusively the only reason for not wanting to do this at this time).
