### ISSUE TITLE
Integrate Thunderbird Conversations with my extension

### ISSUE THREAD

**Issue by jporminal** [protz/thunderbird-conversations#1411]
I want to integrate my extension with thunderbird conversations but the link provided in [this](https://github.com/protz/thunderbird-conversations/wiki/FAQ#interaction-with-other-addons) wiki section is broken. I couldn't find any other documentation on how to do this.

This is the link 
http://blog.xulforum.org/index.php?post/2010/11/27/Thunderbird-Conversations-plugins

**Comment by Standard8** [comment]
I'm sure that worked when I looked the other day...

Anyway, a lot of it depends on what's broken/needs fixing/what you integrate to. We have a few plugins shipped with Conversations as they're some of the bigger add-ons. These can be found here: https://github.com/protz/thunderbird-conversations/tree/master/addon/content/modules/plugins

The hook file describes the notifications you can receive: https://github.com/protz/thunderbird-conversations/blob/master/addon/content/modules/hook.js

Note: you won't get any compose related ones at the moment, as quick reply is disabled.

Plugins can add tags to messages, and show notification bars - there's a few places in the existing plugins that do that.

Also note that due to the WebExtension changes, we're doing a lot of re-organising work at the moment. I suspect at some stage the format of the plugins will need to change, but I haven't yet worked out what that will look like, though I suspect it'll be similar, just via WebExtension APIs.

**Comment by jporminal** [comment]
Thanks a lot!
