### ISSUE TITLE
IMAP folder named "Inbox" troubles

### ISSUE THREAD

**Issue by Silex** [protz/thunderbird-conversations#1467]
* **Thunderbird version: 68.7.0**
* **Thunderbird Conversation version: 3.0.17**
* **Operating System: Windows 10**

**What did you do?**

My inbox has an IMAP folder named "Inbox" at the root.

**What did you expect to happen?**

Everything should just work.

**What actually happened?**

 When I activate the conversation plugin then this "Inbox" folder disappears. To make it come back, I have to open "Subcribe..." on my account, untick it along with another folder, press ok, then reopen "Subscribe" and re-tick everything.

Whenever I close & reopen thunderbird the problem reappars. The fix so far is to rename "Inbox" to "FooInbox" or whatever is not named "Inbox".

Note: this problem did not happen on Ubuntu 18.04

**Comment by Standard8** [comment]
I don't think Conversations is doing anything special with the inbox.

Are you sure this isn't just switching the folder view? e.g. try View -> Folders -> All.

It could be that because it is named Inbox, which I assume is a duplicate of the real Inbox folder, then that's confusing Thunderbird along the way somewhere. Generally, it can be a little precarious having folders named the same as the default ones, though obviously we should probably be able to handle it.

**Comment by Silex** [comment]
> Are you sure this isn't just switching the folder view? e.g. try View -> Folders -> All.

Good catch. This was probably it, it was set to "Unified", while on my linux boxes it was set to "All".

> It could be that because it is named Inbox, which I assume is a duplicate of the real Inbox folder, then that's confusing Thunderbird along the way somewhere. Generally, it can be a little precarious having folders named the same as the default ones, though obviously we should probably be able to handle it.

No my inbox folder is not a duplicate of the real inbox folder. Anyway since I reported this bug the problem is gone with my "FooInbox" folder, but it happened again with other folders... so it was not a problem with "Inbox" per se but with any folders.

Since I just changed the setting to "All" I guess the problem is fixed now, thanks for the suggestion.
