### ISSUE TITLE
Conversations not working properly with 3.0.17 to 3.1.2 upgrade

### ISSUE THREAD

**Issue by upandbeyond** [protz/thunderbird-conversations#1481]
* **Thunderbird version:**
68.8.0
* **Thunderbird Conversation version:**
3.1.2
* **Operating System:**
MacOS 10.15.4

**What did you do?**
Today I was prompted to upgrade Thunderbird Conversations. After upgrading, no matter what, everything is broken and conversations are not grouped together. Have uninstalled and reinstalled numerous times, disabled all other extensions, run the setup assistant numerous times and it still doesn't work. Have followed all instructions on the FAQ. Help!

Thank you!!

**Comment by upandbeyond** [comment]
I also tried enabling debugging and starting from Terminal (open -a Thunderbird) but nothing was printed to terminal. Glodebug extension recommended in troubleshooting is also no longer available. Thanks!

**Comment by Standard8** [comment]
Thank you for the report, I was a little concerned that this might happen, but I'm not quite sure the best way around it. I've disabled the new version on the add-on site for now, I'll reconsider what to do.

You should be able to work with the new version though. If you start Thunderbird with this command, then it'll get you working again:

`/Applications/Thunderbird.app/Contents/MacOS/thunderbird -purgecaches`

It should only be needed once.

**Comment by Standard8** [comment]
For Linux, people can do

`thunderbird -purgeconsole` from the terminal.

**Comment by sparusaurata** [comment]
Thanks for the very quick reply!
Sadly it doesn't seem to work on Linux, but I suppose I can just remove the addon and re-install the previous version.

**Comment by Standard8** [comment]
@sparusaurata argh, sorry, I meant `thunderbird -purgecaches` you might need to prefix it with `/path/to/thunderbird -purgecaches`

**Comment by Standard8** [comment]
Just a few comment about what's happening here.

Thunderbird has a startup cache which provides pre-cached information about the JavaScript files so that it can startup faster.

With the way the most recent versions are working, we're loading files that get saved into that cache. The update for the add-on then comes along, but Thunderbird doesn't clear the cache because it isn't to need to.

We're working on moving away from the fundamental issue, but it is a long process.

In the meantime I've included in 3.1.x a solution for busting the cache on upgrade, so in future it should work more or less seamlessly. Unfortunately that only works for subsequent upgrades and not from the broken one to the new one.

It looks like we've a couple of options: Release an update to 3.0.x that implements only the cache busting, I think we'd get away with that - though we'd probably need to wait until the next Thunderbird minor release before releasing a new 3.1.x version (a minor release of Thunderbird should clear the cache).

The other one is to add cache busting to 3.1.x if it detects an upgrade from the 3.0.x or earlier, and in that case the worst thing would be having to restart Thunderbird.

I think I'll probably do both.

**Comment by sparusaurata** [comment]
> @sparusaurata argh, sorry, I meant `thunderbird -purgecaches` you might need to prefix it with `/path/to/thunderbird -purgecaches`

It still doesn't work... :'-(

**Comment by Standard8** [comment]
That's strange and a shame, but I'm glad the reverting to previous version works for you. Hopefully with the other fixes coming this will work better.

**Comment by Standard8** [comment]
I've just put up for review version 3.0.18 that includes the code for hopefully helping with upgrades. It seems to work for upgrading to 3.1.2, except you do still need a restart of Thunderbird, but at least it should keep working.

I can't do much about the needing restart bit, there's a lot of changes that would be needed but are difficult to do without falling into the same upgrade trap.

So as per the above plan, we'll let that run through until the next version of Thunderbird is out (start of June), and then try upgrade to 3.1.x again with the added fix there as well.

**Comment by upandbeyond** [comment]
> > @sparusaurata argh, sorry, I meant `thunderbird -purgecaches` you might need to prefix it with `/path/to/thunderbird -purgecaches`
> 
> It still doesn't work... :'-( I finally re-installed the previous version.
> Thanks for your answers!

First of all, thanks for the prompt support and for a great extension.

Yeah, it doesn't work for me either ("/Applications/Thunderbird.app/Contents/MacOS/thunderbird -purgecaches") - will try 3.0.18 next!

**Comment by upandbeyond** [comment]
Installed 3.0.18 and at first it didn't work. Restarted with purgecache and now it is working again! Thank you. Also just made a small donation via PayPal, appreciate your work!

**Comment by peckpeck** [comment]
purgecaches doesn't work for me either, if i enable debug messages ang do to the console, here is what i get 

[Exception... "Component returned failure code: 0x80520009 (NS_ERROR_FILE_INVALID_PATH) [nsIFile.target]"  nsresult: "0x80520009 (NS_ERROR_FILE_INVALID_PATH)"  location: "JS frame :: jar:file:///home/me/.thunderbird/f2291bmk.default/extensions/gconversation@xulforum.org.xpi!/experiment-api/contactsApi.js :: getIdentities :: line 185"  data: no] contactsApi.js:185:18
    getIdentities jar:file:///home/me/.thunderbird/f2291bmk.default/extensions/gconversation@xulforum.org.xpi!/experiment-api/contactsApi.js:185
    getIdentities self-hosted:1003
    result resource://gre/modules/ExtensionParent.jsm:1139
    withPendingBrowser resource://gre/modules/ExtensionParent.jsm:770
    result resource://gre/modules/ExtensionParent.jsm:1139
    withTiming resource://gre/modules/ExtensionParent.jsm:1100
    call resource://gre/modules/ExtensionParent.jsm:1138
    AsyncFunctionNext self-hosted:839

**Comment by Standard8** [comment]
@peckpeck any chance you could get a full log from startup? With the debugging option turned on in conversation's preferences.

I'm a little surprised that `purgecaches` isn't working, so I'm starting to wonder if there's something else that is being missed.

**Comment by peckpeck** [comment]
what do you call full log from startup ? How can I get it ?
i got nothing on from the command line,

**Comment by Standard8** [comment]
In Tools -> Add-ons, select preferences next to Thunderbird Conversations, go down to the bottom of the page and make sure "Debugging" is enabled.

Next restart Thunderbird. As soon as it opens, open up the error console (Tools -> Developer Tools -> Error Console). Then also select an email in the main window.

Back in the error console, right-click and select all, then cmd-c (or ctrl-c) to copy everything.

**Comment by peckpeck** [comment]
https://0bin.net/paste/YIC0YthP3hiGwiZL#POQW2M20nV68ZZC8kcLqKqXlvIjSdbJu3Gy1obdHefu

**Comment by peckpeck** [comment]
I tested 3.0.18 and it fails too
I tested 3.0.17 and it works 

Thunderbird: 68.8.0
OS: debian 10

**Comment by Standard8** [comment]
> I tested 3.0.18 and it fails too
> I tested 3.0.17 and it works

I've no idea what that problem is then. 3.0.18 did only two things: 1) fix a small typo in the message display code (9845f36a), 2) Added some extra code which would only get called on uninstall/disable/upgrade of the add-on (efe8a07ca7).

Neither of those should be affected by the application cache, which makes me think you have some other issues.

Have you tried disabling all other add-ons? Is the error message still the same?

**Comment by Standard8** [comment]
@peckpeck @upandbeyond @sparusaurata Would you mind trying this new version before I push it out? There's a few fixes that'll hopefully help.

You'll need to right-click the link and "Save Link As...".

https://www.thebanners.uk/conversations-3.1.3.xpi

You can install it by going to Tools -> Add-ons -> Extensions, then clicking the cog symbol and selecting "Install add-on from file".

You'll probably need to restart for it to work fully.

If it doesn't work, please can you get me the logs as follows, so that hopefully we can narrow down a bit more about what is happening here?

For the logs:

In Tools -> Add-ons, select preferences next to Thunderbird Conversations, go down to the bottom of the page and make sure "Debugging" is enabled.

Next restart Thunderbird. As soon as it opens, open up the error console (Tools -> Developer Tools -> Error Console). Then also select an email in the main window.

Back in the error console, right-click and select all, then cmd-c (or ctrl-c) to copy everything.

**Comment by markovendelin** [comment]
As I have been hit repeatedly with email being marked read, I took a chance and updated from 3.0.18 to 3.1.3; Thunderbird 68.8.1; Linux;

- downloaded the file from the message above;
- installed under extensions; 
- closed Thunderbird
- started Thunderbird

and all worked as it should. I have not used any special arguments either, just regular launcher.

**Comment by peckpeck** [comment]
This time there is no display  at all when i select a mail.
Here are the logs https://pastebin.com/PxwV0QmQ

The last exception is what I get each time I select an email

**Comment by Standard8** [comment]
> This time there is no display at all when i select a mail.
> Here are the logs https://pastebin.com/PxwV0QmQ

Ok, that is interesting. In 3.1.3 I specifically made that function to be included in contactsApi, rather than loaded from a different file.

So that would imply it is still trying to load the old version of contacts API. Weird.

If you haven't already restarted, please could you do so.

Could also try:

* Uninstall conversations.
* Start Thunderbird with `thunderbird -purgecaches`
* Shutdown Thunderbird.
* Start Thunderbird normally.
* Install 3.1.3 again.

**Comment by peckpeck** [comment]
> If you haven't already restarted, please could you do so.
No change

> Could also try:
> ...
Same error as before

**Comment by Standard8** [comment]
> > Could also try:
> > ...
> 
> Same error as before

In the add-on manager, if you click on the Conversations entry, can you just confirm it is definitely 3.1.3 ?

Also, maybe try restarting with all add-ons disabled, then just enabling Conversations. I really don't think it is a conflict of add-ons, but at this stage, I'm at a loss to know what to suggest.

**Comment by peckpeck** [comment]
Yes it is, all other plugins are disabled

**Comment by peckpeck** [comment]
You said :

> So that would imply it is still trying to load the old version of contacts API. Weird.

What are you calling old version of contact api ? It looks like there is only one in the xpi file and i could not find any other reference in my thunderbird configuration directory

**Comment by Standard8** [comment]
> You said :
> 
> > So that would imply it is still trying to load the old version of contacts API. Weird.
> 
> What are you calling old version of contact api ? It looks like there is only one in the xpi file and i could not find any other reference in my thunderbird configuration directory

Yeah, contactApi.js in the xpi should be the only reference to it.

However, you probably won't find it on the configuration directory, there's a cache folder in the profile folder called `startupCache` that may have references to it in one of the files (which are binary based)... however they should be removed/cleaned when `-purgecaches` is specified.

**Comment by peckpeck** [comment]
I got some more data for you : I tried to dump the variables where the error occurs.
You are calling : 
`JSON.parse(JSON.stringify(getIdentities(!includeNntpIdentities)))` in contactsApi.js

* getIdentities returns an object that makes stringify fail
* this object contains a .[0].identity.signature.target object that is an exception
* the exception is `[Exception... "Component returned failure code: 0x80520009 (NS_ERROR_FILE_INVALID_PATH) [nsIFile.target]"  nsresult: "0x80520009 (NS_ERROR_FILE_INVALID_PATH)"  location: "JS frame :: debugger eval code :: <TOP_LEVEL> :: line 1"  data: no]`
* stringify fails on a exception object

**Comment by Standard8** [comment]
Thank you for that. Very interesting.

The `getIdentites()` function is implemented a few lines below the `JSON.parse` etc. Could you add some more to that to see if it is calling into that function or somewhere else?

If it is easier, if you go to Tools -> Developer Tools -> Developer Toolbox, you can then accept the connection, and select the debugger. Do ctrl-P (I think) and search for `contactsApi.js`, you should then be able to add a breakpoint to that file. Try stepping into the function and see what happens...

**Comment by Standard8** [comment]
Or maybe move `getIdentitiesImpl()` after `getIdentities()` and see what happens?

**Comment by peckpeck** [comment]
The object is the account's signature object.
This looks like a bug in thunderbird (mine: v68.8.0 linux). Even removing the account signature is not sufficient.

I worked around the problem with this line in contactsApi.js : 
`JSON.stringify(getIdentities(!includeNntpIdentities), function (k,v) { if (k == "signature") { return null } return v }  )

I couldn't make it remove only the target because it tries to get the full signature object (including the target) before stringifying it.

I hope the signature is not useful in conversation, if so i'd be glad if you could add this workaround

**Comment by Standard8** [comment]
> The object is the account's signature object.
> This looks like a bug in thunderbird (mine: v68.8.0 linux). Even removing the account signature is not sufficient.

Ah, that explains things. You might be able to change things if you go into preferences, Advanced, then hit the Config Editor on the general page - search for signature.

In the meantime, yes we shouldn't be needing the full object there, I think all we really need are just the email addresses. I'll look into simplifying it.

Thank you for identifying that.

**Comment by peckpeck** [comment]
Tweaking the signature preferences doesn't work. I made it work temporarily by removing the sig_file and sig_file-rel from pref.js manually but it is re-added on next restart.

**Comment by Standard8** [comment]
@peckpeck No idea why they keep coming back... anyway, please could you try this version: https://www.thebanners.uk/conversations-3.1.4.xpi

I've made the identity handling only handle emails, which is all it really needs to do (the rest was historical).

Hopefully that works. Need to do a little bit more testing before that ships, but hopefully that'll be a lot better.

**Comment by peckpeck** [comment]
Great, it works for me :+1:

**Comment by Standard8** [comment]
> Great, it works for me 👍

Excellent. Thank you so much for the investigation there. I now see where we went wrong, lesson learnt (hopefully!).

I'm hoping to release the new version soon-ish, though I might wait until the next Thunderbird is released to help with any potential cache clearing issues.

**Comment by peckpeck** [comment]
Thank you

**Comment by Standard8** [comment]
I have just posted 3.1.5 for review - this has a couple of minor performance improvements that I found after posting the 3.1.4 here.

Hopefully they should be out in the next couple of days, and hopefully all the previous upgrade issues will be fixed.

If you do find issues, please file new ones.

**Comment by Standard8** [comment]
Just to follow-up on this, 3.1.6 is now approved and available. Hopefully all the issues are fixed, but if you do see any, please file a new issue.
