### ISSUE TITLE
Unified view of emails folders seems to be disabled on every thunderbird-conversations update

### ISSUE THREAD

**Issue by Porkepix** [protz/thunderbird-conversations#1501]
* **Thunderbird version:** 68.9.0
* **Thunderbird Conversation version:** 3.1.13
* **Operating System:** ArchLinux

**What did you do?**

Nothing, but addon got automatically updated

**What did you expect to happen?**

Nothing special.

**What actually happened?**

Unified view was disabled (all mailboxes in a single view), which is a Thunderbird setting, and was I think enabled by thunderbird-conversations years ago. Now it seems to be disabled after every single update of the addon (it's already 2 or 3 times that it happens). This is a regression from something like two weeks ago.

**Comment by saiarcot895** [comment]
This happened to me as well. I reran the setup assistant (linked from the preferences window for this add-on), and it at least brought back Unified Inbox. Conversation threading, however is broken.

**Comment by Standard8** [comment]
I see what's happening - on upgrade we get shutdown and then started up again. As this isn't application shutdown, we're running the uninstall routines. However, we're then not re-running them after the upgrade is complete...

Unfortunately the newer WebExtension functionality that Thunderbird has, doesn't give us quite as much flexibility as the old system especially wrt uninstall/shutdown.

I'm actually thinking about changing the whole setup assistant/uninstall management system as well.

I'm tempted to make it so that more things are enabled by default (without prompting), and have a different flow for enabling various options.

The critical part there would be the uninstall process - I'm pondering about either providing an "undo changes" type of button in Conversation's preferences, or opening a page to a "here's how to undo changes".

Thoughts welcome, although I will make sure we do at least something for the next update - at a minimum, I think we might be able to re-apply the changes, or just stop the uninstall routing completely.
