### ISSUE TITLE
Conversation reader is failing to load conversations

### ISSUE THREAD

**Issue by vadi2** [protz/thunderbird-conversations#765]
The addon seems to have trouble reading emails - see conversation view below, which does not load anything.

I checked in the error console but there are no errors logged; only warnings in regards to unknown CSS properties.

I've had to disable the addon for now. This is on TB 24 on Ubuntu 13.04, 64bit. I don't have any of the incompatible addons listed in the wiki installed.

I'm using it on an ExQuilla account (connected to Microsoft Exchange).

Is there anything I can help with to debug?

![selection_044](https://f.cloud.github.com/assets/110988/1177298/63b193f6-217d-11e3-894e-b744f8aa26e4.png)

**Comment by justinbleach** [comment]
For anyone that had this issue recently like I did. I made sure I had the most recent release of Thunderbird which as of this is 38.0.1. Even disabling and restarting and re-enabling and restarting did not fix it. I had to actually remove the add-on and go back to the add-on's page, re-add it and then restart to get it to work again.

**Comment by giates** [comment]
Seems that the problem is here again on Linux 17.3/Cinnamon.

After today thunderbird upgrade (v. 45.2.0)

1) If I double click a message thunderbird opens a "Conversation reader" tab and shows "Loading..." but nothing happens.

2) If I right click the message and I select "Open in new tab" or "Open in new window" thunderbird opens and shows the message (the only workaround that I can use to open the messages...).

3) If I start thunderbird from terminal and double click the message the result is the same of number 1 and no error messages are shown into terminal.

**Comment by karfau** [comment]
The same for me, double click to open in new tab doesn't work for me.
Only as @giates says in 2) right click and "Open in new tab", does it, but that doesn't open the Conversation View but the "normal" mail view. Also "Open in new tab" doesn't show up when right clicking a thread (multiple collapsed mails.

**Comment by karfau** [comment]
I fixed the issue for me by removing the add on, restarting Ubuntu (to complete various pending updates) and installing the add on again.

**Comment by giates** [comment]
Solved thanks to @karfau.

Removing the add on and installing the add on again now I can open again the message double clicking on it.

**Comment by venkateshseerapu** [comment]
Me still facing the issue.
After closing and opening the Thunderbird, automatically conversations are not loading.
It's blocking  my work because I'll open all the to do emails and will close once finished.

**Comment by giates** [comment]
@venkateshseerapu I have uninstalled conversationa reader add on and now it works
