### ISSUE TITLE
Messages containing an invitation to an event no longer show Accept/Tentative/Decline buttons

### ISSUE THREAD

**Issue by apippin** [protz/thunderbird-conversations#837]
After upgrading to Thunderbird 31 and Lightning 3.3 and Thunderbird Conversations 2.8, I noticed that the invitation Accept/Tentative/Decline buttons are no longer visible in the message pane. If I open the message containing an invitation in the classic reader, the buttons are there. If I disable Thunderbird Conversations, the buttons appear in the message pane as you'd expect. I didn't start seeing this issue until upgrading as indicated above. Let me know if there is anything else I can do to help with this issue.

**Comment by Danstahr** [comment]
This appears to be broken (again?) for v2.13.4 and Thunderbird 60.

**Comment by Standard8** [comment]
@Danstahr It generally isn't a good idea to comment on long-closed issues even if they re-appear. There might have been an issue previously, but it'll more than likely be a different cause this time. Also a fresh issue is more likely to be noticed whereas comments on old issues are likely to get lost.

In this case the issue was already raised as #1292.

Note that you should be on the 2.14.x series for Thunderbird 60 as 2.13.x is completely incompatible.
