### ISSUE TITLE
Toggle conversation view ON/OFF with one key

### ISSUE THREAD

**Issue by woijtek** [protz/thunderbird-conversations#909]
I would like to have possibility to turn conversation view on and off with just one key using 'keyconfig' addon. What command should I use to make it work?
(e.g. goDoCommand('cmd_conversationView'); or something)

**Comment by protz** [comment]
Can you submit a patch to `monkeypatch.js` so that, in addition to the "View > Conversation View" menu item, the addon also creates a XUL `<command>` element and associates it to the menu item? That's the fix needed for what you want to work.

(I don't have time to work on this and it's fairly non-essential, so quite unfortunately this would be considered low-priority for me right now).

Thanks,

Jonathan

**Comment by Standard8** [comment]
Seeing as we haven't had more requests for this, I'm closing it out. I'd like to keep conversations as simple as possible.
