### ISSUE TITLE
New windows do not contain application menu toolbar items in OSX

### ISSUE THREAD

**Issue by fingres** [protz/thunderbird-conversations#914]
OSX 10.10.1
TB 31.4.0
Conversations 2.8.1

If I open a message in a new window the application menu bar only has the main TB application menu available. This results in being unable to close the window using the usual cmd+w keyboard shortcut.

![screenshot 2015-02-11 12 46 02](https://cloud.githubusercontent.com/assets/2339659/6147228/10b8f9b2-b1ed-11e4-9ed9-c2447c772bc5.png)

**Comment by protz** [comment]
Correct. This is hard to fix, however, because the new window opens a bare XUL chrome that doesn't even have a `<menu>` XUL element, so even if I put "menubar" in the options for my call to `window.open`, it wouldn't know which menu to display.

The (expensive, unaffordable) way to fix this would be to write a custom XUL chrome for those pop-up conversation windows. The (right) way to fix this would be to open messenger.xul, but right now, messenger.xul cannot be used for that purpose and always displays a mail:3pane. There's plans to fix that, though, but it most likely won' thappen in the near future.

Thanks for reporting, though!

Jonathan

**Comment by danduq** [comment]
OK, thanks for the explanation and for getting back to me Johnathan!

**Comment by zzzeek** [comment]
how about an option so that we get "traditional" view for a message that we open in new window?

**Comment by Standard8** [comment]
I believe at the moment, there's no way to open a message in a new window that has the conversations display. Hence closing for now. If it gets added back in the future, this will likely be found anyway.
