### ISSUE TITLE
Feature Request: Copy e-mail addresses

### ISSUE THREAD

**Issue by DaveJarvis** [protz/thunderbird-conversations#966]
There is currently no obvious (and quick) way to copy the list of e-mail addresses on a message. Here's what is possible:
1. Select a message
2. Click _show details_
3. Highlight the e-mail addresses with the mouse
4. Copy the selected text
5. Paste the e-mail addresses

This produces:

```
to: ★ account1@domain.com
★ account2@domain.com
★ account3@domain.com
```

Another way is as follows:
1. Select a message
2. Click _more_
3. Click _view message source_
4. Highlight the e-mail addresses
5. Copy them
6. Paste them

This produces the desired result:

account1@domain.com, account2@domain.com, account3@domain.com

I would like to request an easier (faster) way to copy the e-mail addresses into a comma-separated list. For example:
1. Select a message
2. Right-click the listed e-mail addresses shown
3. Select _Copy e-mail addresses_
4. Paste

This should also produce the desired result:

account1@domain.com, account2@domain.com, account3@domain.com

**Comment by protz** [comment]
Hi,

Thanks for the feedback. I checked and Thunderbird doesn't implement it either. There's a decades-old bug over there at https://bugzilla.mozilla.org/show_bug.cgi?id=327621

Thinking about it, that seems like a moderately valid feature request: in 10 years, there's only been 9 comments on the Thunderbird bug. If people actually wanted that, there would be 300+ comments of people complaining, like in some other bugs. Now the question is do we want more code in Conversations? Because anything you add, I'll have to maintain until the end of times.

The conclusion is thus: if you submit a patch that doesn't take more than a few lines, then sure, why not. Otherwise, this will just remain as an enhancement request.

Thanks,

Jonathan

**Comment by simonschaufi** [comment]
creating/opening the tooltip like in the first line next to the star would already help a lot so that i can create a contact instantly without copy pasting

**Comment by Standard8** [comment]
There's not been more requests for this at the moment, so I'd say no for now. We're rewriting and we need to keep it simple for the time being.
